anigma1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('idea.urls')),
    # url(r'^idea/', include('idea.urls')),
    url(r'^admin/', admin.site.urls)
]

idea/urls.py
from django.conf.urls import url
from . import views

app_name = 'idea'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<idea_id>[0-9]+)/$', views.idea_details, name='idea_details'),
]

idea/models.py
from django.db import models
from django.contrib.auth.models import User
import json

class Profile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.user


class Team(models.Model):
    name = models.CharField(max_length=100)
    members = models.ManyToManyField(User)
    nickname = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Idea(models.Model):
    author = models.ForeignKey(User)
    team = models.ForeignKey(Team)
    title = models.CharField(max_length=100)
    description = models.TextField()
    repository = models.URLField(max_length=150)
    tags = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    def settags(self, x):
        self.tags = json.dumps(x)

    def gettags(self):
        return json.loads(self.tags)

idea/views.py
from django.shortcuts import render, get_object_or_404
from .models import Idea

def index(request):
    all_ideas = Idea.objects.all()
    return render(request, 'idea/home.html', {'all_ideas': all_ideas})

def idea_details(request, idea_id):
    idea = get_object_or_404(Idea, pk=idea_id)
    return render(request, 'idea/idea_details.html', {'idea': idea})

idea/templates/idea/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Idea Pot</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#f6f6f6">
	<div class="container-fluid" style="min-height:95%; ">
		<div class="row">
			  <div class="col-sm-2">
				  <br>
				  <center>
					<img src="{% static 'img/test.jpg' %}" class="responsive-img" style='max-height:100px;' alt="face">
				  </center>
			  </div>
			  <div class="col-sm-10">
				  <br>
				  <center>
				  <h3>Idea Management Homepage</h3>
				  </center>
			  </div>
		</div><hr>

		<div class="row">
		  <div class="col-sm-2">
		  <br>

		  <br>
		   <!-- Great, til you resize. -->
			<!--<div class="well bs-sidebar affix" id="sidebar" style="background-color:#fff">-->
			<div class="well bs-sidebar" id="sidebar" style="background-color:#fff">
			  <ul class="nav nav-pills nav-stacked">
				<li><a href='/'>Home</a></li>
				<li><a href='/blog/'>Blog</a></li>
				<li><a href='/contact/'>Contact</a></li>
			  </ul>
			</div> <!--well bs-sidebar affix-->
		  </div> <!--col-sm-2-->
		  <div class="col-sm-10">
		  
			<div class='container-fluid'>
			<br><br>
			   {% block content %}
			   {% endblock %}	
			</div>
		  </div>
		</div> 
	</div>
	<footer>
		<div class="container-fluid" style='margin-left:15px'>
			<p><a href="#" target="blank">Contact</a> | <a href="#" target="blank">LinkedIn</a> | <a href="#" target="blank">Twitter</a> | <a href="#" target="blank">Google+</a></p>
		</div>
	</footer>	
	
</body>

</html>

idea/templates/idea/home.html
{% extends "idea/header.html" %}

{% block content %}
    <ul>
        {% for idea in all_ideas %}
            <li><a href="{{idea.id}}/">{{idea.title}}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

idea/templates/idea/idea_details.html
{% extends "idea/header.html" %}

{% block content %}
	<strong>Idea Title: </strong> {{idea.title}}<br>
	<strong>Author: </strong>{{idea.author}}<br>
	<strong>Description: </strong>{{idea.description}}<br>
	<strong>Tags: </strong>{{idea.tags}}
{% endblock %}

idea/templates/idea/includes/ideas.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bootstrap 3, from LayoutIt!</title>

    <meta name="description" content="Source code generated using layoutit.com">
    <meta name="author" content="LayoutIt!">

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

  </head>
  <body>

    <div class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<div class="panel-group" id="panel-368911">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title" data-toggle="collapse" data-parent="#panel-368911" href="#panel-element-509800">Collapsible Group Item #1</a>
					</div>
					<div id="panel-element-509800" class="panel-collapse collapse in">
						<div class="panel-body">
							Anim pariatur cliche...
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title" data-toggle="collapse" data-parent="#panel-368911" href="#panel-element-60006">Collapsible Group Item #2</a>
					</div>
					<div id="panel-element-60006" class="panel-collapse collapse">
						<div class="panel-body">
							Anim pariatur cliche...
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						Panel title
					</h3>
				</div>
				<div class="panel-body">
					Panel content
				</div>
				<div class="panel-footer">
					Panel footer
				</div>
			</div>
		</div>
	</div>
</div>

    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/scripts.js"></script>
  </body>
</html>

idea/templates/idea/index.html
{% if all_ideas %}
    <ul>
        {% for idea in all_ideas %}
            <li><a href="{% url 'idea:idea_details' idea.id %}">{{ idea.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>No ideas here</h3>
{% endif %}

idea/templates/idea/index2.html
{% if all_ideas %}
    <ul>
        {% for idea in all_ideas %}
            <li><a href="{% url 'idea:idea_details' idea.id %}">{{ idea.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>No ideas here</h3>
{% endif %}